# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a89c8b779488649dd972404de267347a8a941de28df11e14921d34d8b1440f9fa6130de144ac5f1545e0542def18b613408204baab8e042707382a23f3b845b

test:
  secret_key_base: 07b873a429607bfba5aa1a50a25e5f2de1ea00e29d8508ddcfa3cb949c3ecc5c933994d608690a5ef2ce09e12aba94d9d9f1b07de5c0d169f2c196ce1f01e044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
